name: Android Release

on:
    push:
        tags:
            - 'v*'

permissions:
    contents: write

jobs:
    build:
        name: Build Release APK
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '17'

            -   name: Set up Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Set up Android SDK
                uses: android-actions/setup-android@v3

            -   name: Install Android SDK components (API 36, NDK, CMake) and accept licenses
                shell: bash
                run: |
                    yes | sdkmanager --licenses || true
                    sdkmanager --install \
                        "platform-tools" \
                        "platforms;android-36" \
                        "build-tools;36.0.0" \
                        "ndk;29.0.14033849" \
                        "cmake;3.22.1"

            -   name: Point local.properties to CI Android SDK
                run: |
                    echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

            -   name: Align Gradle JDK with runner JAVA_HOME
                run: |
                    sed -i '/^org\.gradle\.java\.home=/d' gradle.properties
                    echo "org.gradle.java.home=${JAVA_HOME}" >> gradle.properties

            -   name: Make gradlew executable
                run: chmod +x gradlew

            -   name: Build release APK
                run: ./gradlew --no-daemon clean :app:assembleRelease

            -   name: Sign release APK(s)
                uses: r0adkll/sign-android-release@v1
                with:
                    releaseDirectory: app/build/outputs/apk/release
                    signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
                    alias: ${{ secrets.ANDROID_KEY_ALIAS }}
                    keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
                    keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

            -   name: Upload APK artifact (signed)
                uses: actions/upload-artifact@v4
                with:
                    name: app-release-apk
                    path: app/build/outputs/apk/release/*-signed.apk
                    if-no-files-found: error

    release:
        name: Create Draft Release
        needs: build
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            -   name: Download APK artifact
                uses: actions/download-artifact@v4
                with:
                    name: app-release-apk
                    path: artifacts

            -   name: Create GitHub Release (draft) and upload APKs
                uses: softprops/action-gh-release@v2
                with:
                    files: |
                        artifacts/*.apk
                    draft: true
                    tag_name: ${{ github.ref_name }}
                    generate_release_notes: true

                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
